services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'my-app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  db:
    driver: local
